App/models/location.py
from App.database import db

class Location(db.Model):
  __abstract__ = True

  id = db.Column(db.Integer, primary_key=True)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
  latitude = db.Column(db.Float, nullable=False)
  longitude = db.Column(db.Float, nullable=False)


class HomeLocation(Location):

  def __init__(self, user_id, latitude, longitude):
    self.user_id = user_id
    self.longitude = longitude
    self.latitude = latitude

App/models/user.py
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin
from App.database import db

friends = db.Table(
  'friends',
  db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True),
  db.Column('friend_id',
            db.Integer,
            db.ForeignKey('user.id'),
            primary_key=True))


class User(db.Model, UserMixin):
  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.String(50), nullable=False)
  password = db.Column(db.String(120), nullable=False)
  friends = db.relationship('User',
                            secondary='friends',
                            primaryjoin='User.id==friends.c.user_id',
                            secondaryjoin='User.id==friends.c.friend_id',
                            backref='friends_of')
  home_location = db.relationship('HomeLocation',
                                  uselist=False,
                                  backref='user',
                                  cascade='all, delete-orphan')

  def __init__(self, username, password):
    self.username = username
    self.set_password(password)

  def get_json(self):
    return {'id': self.id, 'username': self.username}

  def set_password(self, password):
    """Create hashed password."""
    self.password = generate_password_hash(password, method='sha256')

  def check_password(self, password):
    """Check hashed password."""
    return check_password_hash(self.password, password)

App/controllers/location.py
from App.models import Location, User, HomeLocation
from App.database import db

def create_home_location(user_id, latitude, longitude):
    home_location = HomeLocation(user_id=user_id, latitude=latitude, longitude=longitude)
    db.session.add(home_location)
    db.session.commit()

def update_home_location(user_id, latitude, longitude):
    home_location = HomeLocation.query.filter_by(user_id=user_id).first()
    if home_location:
        home_location.latitude = latitude
        home_location.longitude = longitude
        db.session.commit()

def delete_home_location(user_id):
    home_location = HomeLocation.query.filter_by(user_id=user_id).first()
    if home_location:
        db.session.delete(home_location)
        db.session.commit()

def get_home_location(user_id):
    home_location = HomeLocation.query.filter_by(user_id=user_id).first()
    if home_location:
        return home_location
    return None

App/controllers/user.py
from App.models import User
from App.database import db

def create_user(username, password):
    newuser = User(username=username, password=password)
    db.session.add(newuser)
    db.session.commit()
    return newuser

def get_user_by_username(username):
    return User.query.filter_by(username=username).first()

def get_user(id):
    return User.query.get(id)

def get_all_users():
    return User.query.all()

def get_all_users_json():
    users = User.query.all()
    if not users:
        return []
    users = [user.get_json() for user in users]
    return users

def update_user(id, username):
    user = get_user(id)
    if user:
        user.username = username
        db.session.add(user)
        return db.session.commit()
    return None

#friend controllers
def add_friend(user_id, friend_id):
    user = User.query.get(user_id)
    friend = User.query.get(friend_id)
    if user and friend:
        user.friends.append(friend)
        db.session.commit()

def remove_friend(user_id, friend_id):
    user = User.query.get(user_id)
    friend = User.query.get(friend_id)
    if user and friend:
        user.friends.remove(friend)
        db.session.commit()

def get_friends(user_id):
    user = User.query.get(user_id)
    if user:
        return user.friends
    return []

def are_friends(user_id, friend_id):
    user = User.query.get(user_id)
    friend = User.query.get(friend_id)
    if user and friend:
        return friend in user.friends
    return False

App/views/auth.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user as jwt_current_user
from flask_login import login_required, login_user, current_user, logout_user

from .index import index_views

from App.controllers import (create_user, jwt_authenticate, login)

auth_views = Blueprint('auth_views', __name__, template_folder='../templates')
'''
Page/Action Routes
'''


@auth_views.route('/users', methods=['GET'])
def get_user_page():
  users = get_all_users()
  return render_template('users.html', users=users)


@auth_views.route('/home', methods=['GET'])
@login_required
def get_home_page():
  return render_template('home.html')


@auth_views.route('/identify', methods=['GET'])
@login_required
def identify_page():
  return jsonify(
    {'message': f"username: {current_user.username}, id : {current_user.id}"})


@auth_views.route('/login', methods=['POST'])
def login_action():
  data = request.form
  if current_user.is_authenticated:
    return redirect(url_for('auth_views.get_home_page'))
  user = login(data['username'], data['password'])
  if user:
    login_user(user)
    return redirect(url_for('auth_views.get_home_page'))
  return 'bad username or password given', 401


@auth_views.route('/logout', methods=['POST'])
def logout():
    logout_user()
    return render_template('index.html')


@auth_views.route('/api/users', methods=['GET'])
def get_users_action():
  users = get_all_users_json()
  return jsonify(users)


@auth_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
  data = request.json
  create_user(data['username'], data['password'])
  return jsonify({'message': f"user {data['username']} created"})


@auth_views.route('/api/login', methods=['POST'])
def user_login_api():
  data = request.json
  token = jwt_authenticate(data['username'], data['password'])
  if not token:
    return jsonify(message='bad username or password given'), 401
  return jsonify(access_token=token)


@auth_views.route('/api/identify', methods=['GET'])
@jwt_required()
def identify_user_action():
  return jsonify({
    'message':
    f"username: {jwt_current_user.username}, id : {jwt_current_user.id}"
  })

App/views/location.py
from flask import Blueprint, redirect, render_template, request, send_from_directory, jsonify
from App.models import db
from App.controllers import 

location_views = Blueprint('location_views', __name__, template_folder='../templates')

App/views/user.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user as jwt_current_user
from flask_login import current_user, login_required

from.index import index_views

from App.controllers import (
    create_user,
    jwt_authenticate, 
    get_all_users,
    get_all_users_json,
    jwt_required,
    get_user_by_username
)

user_views = Blueprint('user_views', __name__, template_folder='../templates')

@user_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users)

@user_views.route('/results/<user_list>', methods=['GET'])
def results_page(user_list):
    return render_template('results.html', user_list=user_list)

@user_views.route('/search', methods=['GET', 'POST'])
def user_search():
    username = request.args.get('username')
    user_list = []
    if not username or not username.strip():
        users = get_all_users()
        user_list = [user.get_json() for user in users]
        return redirect(url_for('user_views.results_page', user_list=user_list))
      
    users = get_user_by_username(username)
    if not users:
        return jsonify({'error': 'No users found with that username.'}), 404
      
    return redirect(url_for('user_views.results_page', user_list=users))




  
@user_views.route('/api/users', methods=['GET'])
def get_users_action():
    users = get_all_users_json()
    return jsonify(users)

@user_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
    data = request.json
    create_user(data['username'], data['password'])
    return jsonify({'message': f"user {data['username']} created"})

@user_views.route('/users', methods=['POST'])
def create_user_action():
    data = request.form
    flash(f"User {data['username']} created!")
    create_user(data['username'], data['password'])
    return redirect(url_for('user_views.get_user_page'))

@user_views.route('/static/users', methods=['GET'])
def static_user_page():
  return send_from_directory('static', 'static-user.html')

App/templates/home.html
{% extends "layout.html" %}
{% block title %}Official BeeSafe App{% endblock %}
{% block page %}BeeSafe{% endblock %}

{{ super() }}


{% block content %}
<script>
  function lol() {
  const messages = [
    
"Wear your seatbelt: Always wear your seatbelt when driving or riding in a vehicle. It's one of the easiest and most effective ways to protect yourself in case of an accident.",
    
"Don't drink and drive: Never drive while under the influence of alcohol or drugs. It's not only illegal, but it's also extremely dangerous.",
    
"Keep your eyes on the road: Avoid distracted driving, such as using your phone or eating while driving. Keep your focus on the road and the task at hand.",
    
"Follow the speed limit: Stick to the posted speed limit and adjust your speed for road and weather conditions. Speeding increases your risk of a crash and makes it harder to react in time.",
    
"Use proper safety gear: Whether you're biking, skateboarding, or participating in any other activity, be sure to wear appropriate safety gear such as a helmet, knee pads, and elbow pads.",
    
"Be aware of your surroundings: Stay alert and aware of your surroundings, whether you're walking in a parking lot or hiking in the woods. Know where you are and who is around you.",
    
"Report suspicious activity: If you see something suspicious or potentially dangerous, report it to the appropriate authorities. You could prevent a tragedy from occurring.",
    
"Keep your home secure: Take steps to make your home as secure as possible, such as locking doors and windows, installing security cameras, and using motion-sensor lights.",
    
"Know basic first aid: Learn basic first aid skills, such as CPR and how to treat common injuries. You never know when you might need to use them.",
    
"Stay informed: Stay up to date on safety information and emergency alerts in your area. The more informed you are, the better prepared you will be to handle any situation that arises."
];


  
  const message = messages[Math.floor(Math.random() * messages.length)];
  console.log(message);
  document.getElementById("message").innerHTML = message;
}
</script>
<center>
 <div class="daily-safety-message">
   <h2 id="message">Daily Safety Messages</h2>
   <button onclick="lol()">Generate Message</button>
   <p ></p>
 </div>
</center>

<iframe width="1430" height="500" src="https://www.youtube.com/embed/ANoP89VInx0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<br><br><br>
<footer>
</footer>
{% endblock %}

App/templates/index.html
{% extends "layout.html" %}
{% block title %}Official BeeSafe App{% endblock %}
{% block page %}BeeSafe{% endblock %}

{{ super() }}

{% block content %}
    <div id="signupwrapper">
        <div id="left">
          <h1 id="signupwrapper-supertext">BeeSafe</h1>
          <h2 id="signupwrapper-subtext">Trinidad & Tobago</h2>
        </div>
        <div id="right">
            <form id="signupwrapper-form" action="/login" method="POST">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required><br>
                          
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required><br>
                          
                <input type="submit" value="Log in">
              </form>
        </div>
    </div>
{% endblock %}

App/templates/layout.html
<!doctype html>
<html>
  <head>
  
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="{{ url_for('static', filename='main.css') }}"></script>
    <script src="{{ url_for('static', filename='script.css') }}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
    <script src="https://kit.fontawesome.com/f42f4f2d2f.js" crossorigin="anonymous"></script>
     <!--Import Google Icon Font-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>

<style>
    footer {
      text-align: center;
      padding: 3px;
      background-color:#5a189a;
      color: white;
    }
  
</style>
  </head>
    
  </head>
  <body>
    <nav class="navbar">
      {% if not current_user.is_authenticated %}
      <div class="navbar-container">
        <div class="navbar-item">
          <a href="/"><i class="fa-solid fa-house"></i></a>
        </div>
      {% endif %}
      {% if current_user.is_authenticated %}
      <div class="navbar-container">
        <div class="navbar-item">
          <a href="/home"><i class="fa-solid fa-house"></i></a>
        </div>
                <div class="navbar-item">
                  <div class="search-container">
                    <form action="/search">
                      <input type="text" name="username" placeholder="Search...">
                      <button type="submit" class="flat-button">Go</button>
                    </form>
                  </div>
                </div>
                <div class="navbar-item">
                  <form action="{{ url_for('auth_views.logout') }}" method="POST">
            <button type="submit" class="icon-button">
                <i class="fa-solid fa-right-from-bracket"></i>
            </button>
        </form>        
                </div>
        {%endif%}
        {% if not current_user.is_authenticated %}
          
        
          <div class="navbar-item" style="height: 5vh">
            <a href="https://form.jotform.com/231138526435050"><p>Sign Up</p></a>
          </div>
        {% endif %}
      </div>
    </nav>
    
    {% with messages = get_flashed_messages() %}
      {% if messages %}
      <nav class="white black-text" style="padding: 10px">
        <div class="nav-wrapper">
            <ul class="flashes">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
        </div>
      </nav>
      {% endif %}
    {% endwith %}

    <div class="container" id="content">{% block content %}{% endblock %}</div>

    <script src="https://maps.googleapis.com/maps/api/js?key=4619-4005-2363-6030"></script>





    
 </body>
    <footer>
    <div>
      <ul class="social media">
        <a href="https://www.facebook.com/people/BeeSafe/100080075097744/"><i class="fa-brands fa-facebook-square"></i></a>
        <a href="https://www.instagram.com/beesafe_tt/"><i class="fa-brands fa-instagram-square"></i></a>
       </ul>
  </div>
  </footer>
</html>

App/templates/location.html
<html> 
<head>
</head>
  
<body>

<div id="map"></div>

<form>
  
  <label for="address">Address:</label>
  <input type="text" id="address" name="address">
  <button type="submit">Submit</button>
</form>
</body>

</html>

App/templates/results.html
{% extends "layout.html" %}
{% block title %}Official BeeSafe App{% endblock %}
{% block page %}BeeSafe{% endblock %}

{{ super() }}

{% block content %}
  {% for user in user_list %}
  <div class="card">
    <p>Username: {{ user.username }}</p>
  </div>
{% endfor %}

<br><br><br>
<footer>
</footer>
{% endblock %}

App/templates/settings.html
<html>

<form action="update.php" method="POST">
  <label for="password">New Password:</label>
  <input type="password" id="password" name="password"><br>

  <label for="location">New Location:</label>
  <input type="text" id="location" name="location"><br>

  <input type="submit" value="Update">
</form>

</html>

App/templates/signup.html
{% extends "layout.html" %}
{% block title %}Official BeeSafe App{% endblock %}
{% block page %}BeeSafe{% endblock %}

{{ super() }}


{% block content %}
<div id="signupwrapper">
  <div id="left">
    <h1 id="signupwrapper-supertext">BeeSafe</h1>
    <h2 id="signupwrapper-subtext">Trinidad & Tobago</h2>
  </div>
  <div id="right">
    <form id="signupwrapper-form" action="/signup" method="POST">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required><br>
                
      <label for="password">Password:</label>
      <input type="password" id="password" name="password" required><br>
                
      <input type="submit" value="Sign up">
    </form>
  </div>
</div>
{% endblock %}

App/templates/users.html
{% extends "layout.html" %}
{% block title %}App Users{% endblock %}
{% block page %}App Users{% endblock %}

{{ super() }}

{% block content %}
    <div class="row">
        <p>
            This is table is renderd on the Server. Flask gets the data from the database and uses jinja templates to dyanmically render this page when a request is sent to <a href="/users">/users</a>.
        </p>
    </div>

    <div class="row">
      <form class="col s12" method="POST" action="/users">
        
        <div class="row">
          <div class="input-field col s6">
            <input placeholder="Username" name="username" type="text" class="validate">
            <label for="username">Username</label>
          </div>
          <div class="input-field col s6">
            <input placeholder="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
      
        <div class="row">
          <div class="input-field col s12">
            <button class="btn waves-effect waves-light right purple" type="submit" name="action">Submit</button>
          </div>
        </div> 

      </form>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Id</th><th>Username</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>

{% endblock %}